### ISSUE TITLE
More of a question than a bug

### ISSUE THREAD

**Issue by impascab** [rembertmagri/pi-control-panel#134]
I've installed this on an OrangePi lite and can't seem to login into the WebUI. I've tried my root login, I tried creating a user named pi with a password but no luck, tried logging in with the default orangepi user (kind of like the default pi users on rpi), and i've also tried logging in with picontrolpanel/picontrolpanel.

Any clues?

**Comment by rembertmagri** [comment]
@impascab What OS are you using? If it's Debian, it should work using your Linux credentials.
