### ISSUE TITLE
Add possibility to change port

### ISSUE THREAD

**Issue by KamilLenica** [rembertmagri/pi-control-panel#93]
**Is your feature request related to a problem? Please describe.**
When running many services it may be an address collision, changing of port on which service is running should be possible

**Describe the solution you'd like**
Add possibility to change port on which service is running, prefferably in config file

**Describe alternatives you've considered**
Make service deployable in docker container

**Comment by AkashRajvanshi** [comment]
src/Docker/docker-compose.pi.yml

**Comment by KamilLenica** [comment]
> src/Docker/docker-compose.pi.yml

So maybe author should add project to docker hub

**Comment by rembertmagri** [comment]
It is now possible to change the port after installing editing the /opt/picontrolpanel/Configuration/appsettings.json. 

Still missing port check during installation

**Comment by rembertmagri** [comment]
Port check during installation implemented on release 1.35
